services:
  chasqui-server:
    # automatically pull the correct image for user architecture (x86, ARM64, or ARMv7)
    image: ghcr.io/${GITHUB_USER:-aur9ra}/chasqui-server:${IMAGE_TAG:-latest}
    container_name: chasqui-backend
    restart: unless-stopped
    networks:
      chasqui_network:
        aliases:
          - chasqui-server
          - chasqui-backend
    ports:
      - "3003:3000"
    volumes:
      - ./db:/db
      - ./content:/content
      - chasqui_dist:/dist
    env_file:
      - .env.containers.default
      - .env.default

networks:
  chasqui_network:
    name: chasqui_network
    external: true # assumes a separate manager or the frontend created the network

volumes:
  chasqui_dist:
    name: chasqui_dist
    external: true # assumes a separate manager or the frontend created the volume
