version: '3.8'

services:
  chasqui-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARCH=${ARCH:-armv7-unknown-linux-musleabihf}
    container_name: chasqui-backend
    restart: unless-stopped
    networks:
      - chasqui_network
    ports:
      - "3003:3000"
    volumes:
      - ./db:/db
      - ./content:/content
      - chasqui_dist:/dist
    env_file:
      - .env.containers.default
      - .env.default

networks:
  chasqui_network:
    external: true

volumes:
  chasqui_dist:
    external: true
