services:
  chasqui-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ARCH=${ARCH:-armv7-unknown-linux-musleabihf}
    container_name: chasqui-server
    restart: unless-stopped
    environment:
      - DOCKER_RUNTIME=true
    networks:
      - chasqui_network
    ports:
      - "${HOST_PORT:-3003}:${PORT:-3003}"
    volumes:
      - chasqui_db:/db
      - ${CONTENT_HOST_PATH:-./content}:/content
    env_file:
      - .env.default
      - .env.containers.default
      - .env

networks:
  chasqui_network:
    external: true

volumes:
  chasqui_db:
    name: chasqui_db
  chasqui_dist:
    name: chasqui_dist
    external: true
